tasks/Orochi/script_task.py
=> fix(Orochi): refactor the logic of detecting dead room

tasks/GoryouRealm/assets.py, tasks/GoryouRealm/gr/ocr.json, tasks/RealmRaid/script_task.py
=> fix: Change the roi of ticket of GoryouRealm.

tasks/Exploration/script_task.py
修复探索任务卡结算界面的问题。修改后无论是否设置锁定队伍都不会在战斗中卡住
=> Fix exploration #171

tasks/CollectiveMissions/assets.py, tasks/CollectiveMissions/cm/ocr.json
=> 寮任务完成次数识别区域更新（含开发工具）

module/device/connection.py, module/device/method/droidcast.py, module/device/method/uiautomator_2.py
同步alas代码，修复Droidcast_raw在mumu12上的截图问题 https://github.com/runhey/OnmyojiAutoScript/issues/244
=> Fix: [OAS] DroidCast image orientation on MuMu12

tasks/Component/SwitchSoul/switch_soul.py
修复切换御魂时 只会滑动一次的BUG, 现在可以正确的滑动到最顶部
由于多开模拟器卡顿造成的:
1. 预设按钮多次点击造成切换御魂失败
2. 切换御魂出现的确定对话框无法关闭导致的卡死
=> fix(SwitchSoul)切换御魂问题

tasks/KekkaiUtilize/assets.py, tasks/KekkaiUtilize/script_task.py, tasks/KekkaiUtilize/utilize/ocr.json
=> 结界收取经验适配开启招财上宾

tasks/ActivityShikigami/assets.py
=> [当期爬塔]:999战斗入口位置修改

tasks/AbyssShadows/script_task.py
fix(AbyssShadows):fix SwitchSoul
=> fix(AbyssShadows):fix SwitchSoul

tasks/AbyssShadows/script_task.py
终于在日志里出现了一次，说明修复生效了
`2024-11-16 21:06:59.505 |       script_task.py:0403 |  WARNING | Failed to enter fire`
=> 修复狭间点击前往按钮偶尔无效

tasks/Restart/login.py
change the condition of login check
=> Changes:fix the bug of login

module/atom/image.py
=> pref[module]:检查图片尺寸是否能够进行匹配，以免发生错误

tasks/EternitySea/script_task.py
=> fix(ScriptTask): Ensure success status is returned for ALONE user status

tasks/Component/SwitchSoul/switch_soul.py, tasks/KekkaiActivation/script_task.py
=> fix(KekkaiActivation): Improve best card selection logic for KekkaiActivation

tasks/Secret/script_task.py
=> 修复秘闻参数名称错误

tasks/GuildBanquet/script_task.py
原来不知道appear的internal间隔没到会返回False......
现在修复，但还没测过
=> fix(GuildBanquet):修复等待宴会

tasks/GuildBanquet/script_task.py
=> fix(GuildBanquet):修复配置出错， 优化日志输出

tasks/GuildBanquet/script_task.py
=> fix(GuildBanquet)：修复宴会时间检测逻辑

tasks/HeroTest/script_task.py
修复此：https://github.com/runhey/OnmyojiAutoScript/issues/714
=> fix(HeroTest): 修复结算时可能点击到掉落物品的问题

tasks/SixRealms/config.py, tasks/SixRealms/script_task.py
=> 六道之门 增加御魂预设2

tasks/Component/Costume/costume_base.py
- 使用字典推导式简化主界面皮肤模型的生成逻辑
- 采用循环和特例处理相结合的方式重构战斗主题模型
- 通过动态获取属性和字符串格式化，提高代码的可维护性和可扩展性
=> refactor(Component/Costume):优化皮肤和战斗主题模型的代码结构

tasks/Secret/script_task.py
小号刚用这个秘闻部分，出现无法切换阵容问题。不确定其他人是否有
=> 修复秘闻无法切换阵容问题

tasks/SoulsTidy/script_task.py
=> add screenshot

tasks/Dokan/script_task.py
=> 修复进入道馆时无限循环

tasks/Component/ReplaceShikigami/replace_shikigami.py
修复循环最主要的文件忘了commit了，，(((请尽快合
因为比较急没看timer用法，之后有空或者谁有时间再改，先解决主要问题.
超时时间最好加一个可传参数，120秒不一定好，因为蹭卡和挂卡都是用这个函数，之后有时间我再来修（
@runhey
=> 紧急修复：寄养无限循环漏commit了一个文件

module/device/method/nemu_ipc.py, module/device/platform2/emulator_windows.py, module/device/platform2/platform_base.py
=> feat(device): 支持 MuMu Player 5.0

module/server/updater.py, script.py
fix oas schedule and updater branch name
=> fix: schedule not broadcast to oasx and branch not replace \n

module/server/updater.py, script.py
(cherry picked from commit 43e9f62d6772edc6c43483fdfd051899c6b8ba06)
=> change push to dev

tasks/Component/GeneralBattle/assets.py, tasks/KekkaiActivation/a/image.json, tasks/KekkaiActivation/assets.py
=> fix kekkai
